// @generated by tools/tidy — do not edit.
// Run `cargo run -p tidy -- --update` to regenerate.
//
// Every #[utoipa::path] route declared across the slices, normalized
// to the served form (/api prefix). The router test checks this set
// against the live spec, so doc and router cannot drift.
#[cfg(test)]
pub(crate) const DECLARED_API_PATHS: &[&str] = &[
    "/api/auth/login",
    "/api/auth/logout",
    "/api/auth/me",
    "/api/auth/password-reset/confirm",
    "/api/auth/password-reset/request",
    "/api/auth/register",
    "/api/stores",
    "/api/stores/reorder",
    "/api/stores/{id}",
    "/api/stores/{storeId}/locations",
    "/api/stores/{storeId}/locations/{locationId}",
];
