pub(crate) mod auth;
pub(crate) mod posts;
pub(crate) mod users;

#[cfg(test)]
pub(crate) mod test_support;

// Generated by tools/tidy (routes' #[utoipa::path] attrs); the router test
// compares this set against the live spec. Regenerate with `cargo run -p tidy -- --update`.
#[cfg(test)]
pub(crate) mod declared_paths;
