use axum::Json;
use axum::routing::get;
use time::Duration;
use tower_governor::GovernorLayer;
use tower_governor::governor::GovernorConfigBuilder;
use tower_sessions::{Expiry, SessionManagerLayer};
use tower_sessions_sqlx_store::PostgresStore;
use utoipa::OpenApi;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa_axum::router::OpenApiRouter;

use crate::error::ErrorBody;
use crate::features;
use crate::state::AppState;

#[derive(OpenApi)]
#[openapi(
    info(title = "rustweb", version = "0.1.0", description = "Axum + SeaORM VSA example"),
    tags(
        (name = "users", description = "User management"),
        (name = "posts", description = "Posts owned by the authenticated user"),
        (name = "auth", description = "Register, login, logout, current-user, and password reset"),
    ),
    components(schemas(ErrorBody)),
    modifiers(&SecuritySchemes),
)]
struct ApiDoc;

/// Declares the session cookie as an `OpenAPI` security scheme so protected
/// handlers can reference it with `security(("session_cookie" = []))`.
struct SecuritySchemes;

impl utoipa::Modify for SecuritySchemes {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "session_cookie",
                SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::with_description(
                    "id",
                    "Session cookie issued by /auth/login or /auth/register",
                ))),
            );
        }
    }
}

/// The full HTTP application, testable end-to-end without a listener.
pub(crate) fn app_router(state: AppState, session_store: PostgresStore) -> axum::Router<()> {
    // `Secure` must be on behind TLS. Plain HTTP dev servers would silently
    // drop the cookie, so it defaults off; set `COOKIE_SECURE=1` in prod.
    let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(state.config.cookie_secure)
        .with_expiry(Expiry::OnInactivity(Duration::days(14)));

    // The per-IP GCRA bucket applied to every `/auth/*` route: register,
    // login, logout, me, and password reset. Credential-stuffing and
    // enumeration attacks all land here, so auth is throttled while the rest
    // of the API stays open. Keyed on the peer IP of the TCP connection (see
    // `main` for the `ConnectInfo` requirement); behind a reverse proxy the
    // peer is the proxy, so all of its users share one bucket — deploy the
    // proxy with a sanitized `X-Forwarded-For` and swap in
    // `SmartIpKeyExtractor` when that matters.
    let governor_config = GovernorConfigBuilder::default()
        .per_second(state.config.auth_rate_limit_per_second)
        .burst_size(state.config.auth_rate_limit_burst)
        .use_headers()
        .finish()
        .unwrap_or_else(|| {
            panic!("invalid rate limit config — Config validated the values at startup")
        });

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(features::users::routes())
        .merge(features::posts::routes())
        .merge(features::auth::routes().layer(GovernorLayer::new(governor_config)))
        .split_for_parts();

    router
        .layer(session_layer)
        .route(
            "/openapi.json",
            get(move || {
                let api = api.clone();
                async move { Json(api) }
            }),
        )
        .with_state(state)
}

#[cfg(test)]
mod tests {
    use std::error::Error;
    use std::sync::Arc;

    use axum::body::Body;
    use axum::http::{Method, StatusCode};

    use crate::features::declared_paths::DECLARED_API_PATHS;
    use crate::features::test_support::{
        TestMailer, app_router, app_router_with, json_body, request, request_from, test_config,
        test_db,
    };

    /// Every route declared in a `#[utoipa::path]` attribute must actually be
    /// served in the spec — and nothing may be served that isn't declared —
    /// otherwise the doc and the router drift silently. The declared set is
    /// generated by `tools/tidy` from the attributes themselves, so adding a
    /// route needs no hand-maintained list here.
    #[tokio::test]
    async fn openapi_spec_serves_every_declared_path() -> Result<(), Box<dyn Error>> {
        let (db, store, _guard) = test_db().await?;
        let app = app_router(db, store);

        let res = request(app, Method::GET, "/openapi.json", None, None).await?;
        assert_eq!(res.status(), StatusCode::OK);
        let spec: serde_json::Value = json_body(res).await?;
        let paths = spec
            .get("paths")
            .and_then(serde_json::Value::as_object)
            .ok_or_else(|| std::io::Error::other("spec is missing paths"))?;

        for path in DECLARED_API_PATHS {
            assert!(
                paths.contains_key(*path),
                "missing path {path} in served spec"
            );
        }
        assert_eq!(
            paths.len(),
            DECLARED_API_PATHS.len(),
            "spec serves a path that no #[utoipa::path] declares \
             (run `cargo run -p tidy -- --update`)"
        );
        Ok(())
    }

    #[tokio::test]
    async fn unknown_route_is_not_found() -> Result<(), Box<dyn Error>> {
        let (db, store, _guard) = test_db().await?;
        let app = app_router(db, store);

        let res = request(app, Method::GET, "/nope", None, None).await?;
        assert_eq!(res.status(), StatusCode::NOT_FOUND);
        Ok(())
    }

    fn login_body() -> Body {
        Body::from(
            serde_json::json!({
                "email": "nobody@example.com",
                "password": "hunter2hunter2",
            })
            .to_string(),
        )
    }

    /// A tight bucket (burst 2, refill 1/s) must throttle the third auth
    /// request, while non-auth routes stay unaffected.
    #[tokio::test]
    async fn auth_routes_are_rate_limited_per_ip() -> Result<(), Box<dyn Error>> {
        let (db, store, _guard) = test_db().await?;
        let mut config = test_config();
        config.auth_rate_limit_burst = 2;
        config.auth_rate_limit_per_second = 1;
        let mailer: Arc<dyn crate::mail::Mailer> = Arc::new(TestMailer::new());
        let app = app_router_with(db, store, config, mailer);

        for _ in 0..2 {
            let res = request(
                app.clone(),
                Method::POST,
                "/auth/login",
                Some(login_body()),
                None,
            )
            .await?;
            assert_eq!(res.status(), StatusCode::UNAUTHORIZED);
        }
        let res = request(
            app.clone(),
            Method::POST,
            "/auth/login",
            Some(login_body()),
            None,
        )
        .await?;
        assert_eq!(res.status(), StatusCode::TOO_MANY_REQUESTS);

        // The exhausted auth bucket must not spill onto other routes.
        let res = request(app, Method::GET, "/users", None, None).await?;
        assert_eq!(
            res.status(),
            StatusCode::UNAUTHORIZED,
            "non-auth routes are not rate limited"
        );
        Ok(())
    }

    /// Two different peer IPs must not share a bucket, even with the same
    /// tight limits.
    #[tokio::test]
    async fn rate_limit_is_keyed_per_ip() -> Result<(), Box<dyn Error>> {
        use std::net::{IpAddr, Ipv4Addr, SocketAddr};

        let (db, store, _guard) = test_db().await?;
        let mut config = test_config();
        config.auth_rate_limit_burst = 1;
        config.auth_rate_limit_per_second = 1;
        let mailer: Arc<dyn crate::mail::Mailer> = Arc::new(TestMailer::new());
        let app = app_router_with(db, store, config, mailer);

        let first_ip = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)), 1234);
        let second_ip = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2)), 1234);
        let res = request_from(
            app.clone(),
            Method::POST,
            "/auth/login",
            Some(login_body()),
            None,
            first_ip,
        )
        .await?;
        assert_eq!(res.status(), StatusCode::UNAUTHORIZED);
        // A second request from the same IP is already over the burst of 1…
        let res = request_from(
            app.clone(),
            Method::POST,
            "/auth/login",
            Some(login_body()),
            None,
            first_ip,
        )
        .await?;
        assert_eq!(res.status(), StatusCode::TOO_MANY_REQUESTS);
        // …while a fresh IP still has its full bucket.
        let res = request_from(
            app,
            Method::POST,
            "/auth/login",
            Some(login_body()),
            None,
            second_ip,
        )
        .await?;
        assert_eq!(res.status(), StatusCode::UNAUTHORIZED);
        Ok(())
    }
}
